(
    MAIN_MENU,
    SELECT_SALON,
    SELECT_MASTER,
    SELECT_PROCEDURE,
    SELECT_DATE,
    SELECT_TIME,
    CLIENT_NAME,
    CLIENT_PHONENUMBER,
    PROMO,
    APPOINTMENT,
    AFTER_APPOINTMENT
) = range(11)
