# Generated by Django 6.0.1 on 2026-01-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram ID'),
        ),
    ]
