# Generated by Django 6.0.1 on 2026-01-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_client_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.promo', verbose_name='Промокод'),
        ),
    ]
