# Generated by Django 6.0.1 on 2026-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_appointment_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='repeat_offer_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено предложение повторной записи'),
        ),
    ]
